import type React from "react";
import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import { Sidebar } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "SannseFashion | Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

   <>
      <Header />
      <div className="flex">
        <Sidebar />
        <div className="w-full mt-[80px] p-6 bg-[#EDEEF1]">{children}</div>
      </div>
   </>
 
  );
}
